// Generated by scripts/abi.mjs from out/MultiSendCallOnly.sol/MultiSendCallOnly.json. Do not edit.
export const multiSendCallOnlyAbi = [
  {
    "type": "function",
    "name": "multiSend",
    "inputs": [
      {
        "name": "transactions",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  }
] as const;
