// Regenerates src/abi/*.ts from Foundry artifacts. Run `forge build` at the repo root first.
import { readFileSync, writeFileSync } from "node:fs";

const OUT = new URL("../../../out/", import.meta.url);
const TARGET = new URL("../src/abi/", import.meta.url);

const ARTIFACTS = [
  { artifact: "RotationGuard.sol/RotationGuard.json", name: "rotationGuardAbi", file: "rotationGuard.ts" },
  { artifact: "Safe.sol/Safe.json", name: "safeAbi", file: "safe.ts" },
  { artifact: "MultiSendCallOnly.sol/MultiSendCallOnly.json", name: "multiSendCallOnlyAbi", file: "multiSendCallOnly.ts" },
];

for (const { artifact, name, file } of ARTIFACTS) {
  const { abi } = JSON.parse(readFileSync(new URL(artifact, OUT), "utf8"));
  const body = `// Generated by scripts/abi.mjs from out/${artifact}. Do not edit.\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(new URL(file, TARGET), body);
  console.log(`wrote src/abi/${file} (${abi.length} entries)`);
}
